parameters:
#    finishme_finishme.example.class: FinishmeBundle\Example

services:
#    finishme_finishme.example:
#        class: %finishme_finishme.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
